"""empty message

Revision ID: 731fcf0a4d81
Revises: 014098214180
Create Date: 2020-08-15 19:53:35.875769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731fcf0a4d81'
down_revision = '014098214180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('gener', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'gener')
    # ### end Alembic commands ###
