"""empty message

Revision ID: 7d90299f44b3
Revises: 731fcf0a4d81
Create Date: 2020-08-15 19:54:10.464741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d90299f44b3'
down_revision = '731fcf0a4d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'gener')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('gener', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
