"""empty message

Revision ID: b66b601baa0f
Revises: 7d90299f44b3
Create Date: 2020-08-15 19:56:34.259210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66b601baa0f'
down_revision = '7d90299f44b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.Integer(), nullable=False),
    sa.Column('movie_genrs', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'actor_in_movie', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actor_in_movie', type_='foreignkey')
    op.drop_table('movie')
    # ### end Alembic commands ###
