"""empty message

Revision ID: ef5dc3d4cf0b
Revises: b66b601baa0f
Create Date: 2020-08-26 23:20:34.774457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5dc3d4cf0b'
down_revision = 'b66b601baa0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor_in_movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_in_movie',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], name='actor_in_movie_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='actor_in_movie_movie_id_fkey'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id', name='actor_in_movie_pkey')
    )
    # ### end Alembic commands ###
